[package]
name = "basic_prod_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde = {version="1.0.228",features=["derive"]}
serde_json = "1.0.145"
tokio = {version="1.48.0",features=["full"]}
tower = "0.5.2"
tower-http = "0.6.6"
