[package]
name = "todo_application"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version="0.8.6",features=["macros"]}
serde = {version="1.0.228",features=["derive"]}
serde_json = "1.0.145"
tokio = {version="1.48.0",features=["full"]}
tower = "0.5.2"
tower-http = {version="0.6.6",features=["trace"]}
tracing = "0.1.41"
tracing-subscriber = {version="0.3.20",features=["fmt","env-filter"]}
