[package]
name = "simple_actix_app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = {version="1.0.219",features = ["derive"]}
serde_json = {version="1.0.140"}
tokio = {version="1",features = ["full"]}
uuid = {version="1.16.0",features = ["v4"]}
